### ISSUE TITLE
Pages and menus autogenerate entries?

### ISSUE THREAD

**Issue by artelse** [myst729/Vuelog#14]
Have been looking at a few node cms/blog options. What I am wondering about with Vuelog is why we need to manually add pages and menu items in a database file. Other systems just generate these from markdown metadata. Look say at Gatsby.
For the rest it looks like a compelling system.

**Comment by myst729** [comment]
The build process in Jekyll or Hexo is like, set up a node service, read MD files from the file system, parse MD files and generate site topology, dump to HTML files.

Vuelog is designed to not have the build process (please read https://myst729.github.io/Vuelog/#/page/about for my reasons), so there's no way to access the file system. That's why we need the **database** - track paths of the MD files.

Without the build process, retrieving a post's metadata becomes more expensive - get the MD file path, request the MD file, and parse the MD file. Sometimes we only need the metadata (the archive view typically), to request bunch of MD files is a big waste, so I move metadata to the database too. Although this introduces extra redundancies, the number of (unnecessary) network requests are reduced.

**Comment by artelse** [comment]
Ok, thanks for the explanation. I am looking for a static builder with Vue and node, so continue my search.

**Comment by myst729** [comment]
To me [nuxt.js](https://github.com/nuxt/nuxt.js) is a promising project, you could give it a try.
