### ISSUE TITLE
pt-BR Translation

### ISSUE THREAD

**Issue by GabrielCoelho** [myst729/Vuelog#24]
## Presentation

Hello, I'm **Gabriel Coelho Soares**, I live in Brazil, born and raised here. I'm a web developer by love and I was searching for static site generators builds with Vue and end up here. 
Loved the idea and started to translate all the documentation provided in [the website][link1]. 
By now, I've already translated all the posts and, as here in Brazil it is 03:14 o'clock, I have to sleep and I'll continue the translation tomorrow. 

I really want to learn Vue, and I have a little conference here in my city this saturday (18) which the subject is "Creating VueJS Applications" (_That's why I was searching for static site generators_). 

So, by now, I cannot help much on the development, but any new documentation post, I'll translate! 

## About the Pul Request

I'm gonna do a PR now, only with the `/posts` and `database.js` file. I'll keep going with pages and I'm pretty sure that before 13:30 here in Brazil (GMT -2) that will be finished. 

Have a nice day :+1: 

![bitmoji](https://render.bitstrips.com/v2/cpanel/6ef96fa9-38f0-41da-94bf-4b19528fad4d-e59a9c2d-40db-4acf-9d35-9c434ed8b493-v1.png?transparent=1&palette=1&width=183)

[link1]: https://vuelog.js.org/#/home

**Comment by myst729** [comment]
That's awesome!

I guess I should update a section for contributing translations. Didn't do that because there was no such contributions before ( #23 was the first one, only 4 days ago). Anyway, here's a list of files that should be modified or created.

- /src/i18n/locale_pt-br.js (create)
- /src/i18n/locales.js
- /userdata/pages/*
- /userdata/posts/*
- /userdata/database.js

By the way, Vuelog is hardly a "static site generator". Unlike Hexo or Jekyll, it doesn't actually "generate" anything with a build process, but that's just something I wanted 😃.
