### ISSUE TITLE
Use with Lunr

### ISSUE THREAD

**Issue by vaughanwatson** [myst729/Vuelog#27]
Hi Leo,
Is there any chance of you integrating Lunr or ElasticLunr and Grunt as part of the basic package to enable some kind of search feature on the markdown files directories out of the box?

**Comment by myst729** [comment]
Never heard of Lunr, let me see.

**Comment by myst729** [comment]
https://myst729.github.io/playground/

Just wrote a demo with Lunr, looks like interesting. But it somehow behaves weird. For instance, searching **wild** will partially match **Wilde**, others don't. Searching **you** or **your** doesn't match anything.

Not sure how to integrate with Vuelog, since it requires pre-defined indices. But Vuelog doesn't have a build process, all markdown contents are fetched on requested. Any ideas?

**Comment by myst729** [comment]
The reason I don't want Grunt (or Gulp, Webpack, etc.) has been addressed [here](https://vuelog.js.org/#/page/about/). Regarding current situation, I think Hexo might be a better choice for you.
